services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: harbor.vgregion.se/senslab/im-interface:latest
        container_name: im-interface
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - app-network
        depends_on:
            - db
        command: sh -c "composer update && php artisan key:generate --force && php artisan migrate --force && php artisan db:seed --force && php-fpm"
        environment:
            DB_HOST: db
        ports:
            - "9000:9000"
    db:
        image: harbor.vgregion.se/senslab/mysql:8.0
        container_name: mysql-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: iim_interface
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        networks:
            - app-network

    nginx:
        image: harbor.vgregion.se/senslab/nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
