apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-interface-deployment
  namespace: im-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: im-interface
  template:
    metadata:
      labels:
        app: im-interface
    spec:
      imagePullSecrets:
        - name: harbor
      containers:
        - name: im-interface
          image: harbor.vgregion.se/senslab/im-interface:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /var/log/nginx /var/log/php7.4 || exit 1;
              chown -R www-data:www-data /var/log/nginx /var/log/php7.4 || exit 1;
              chown -R www-data:www-data /var/www || exit 1;
              composer update || exit 1;
              php artisan key:generate --force || exit 1;
              php artisan migrate --force || exit 1;
              php artisan db:seed --force || exit 1;
              php-fpm || exit 1;
              nginx -g 'daemon off;' || exit 1;
          env:
            - name: DB_HOST
              value: mysql-db
            - name: DB_DATABASE
              value: iim_interface
            - name: DB_USERNAME
              value: user
            - name: DB_PASSWORD
              value: password
          ports:
            - containerPort: 9000
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
