apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-interface-deployment
  namespace: im-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: im-interface
  template:
    metadata:
      labels:
        app: im-interface
    spec:
      imagePullSecrets:
        - name: harbor
      initContainers:
        - name: init-setup
          image: harbor.vgregion.se/senslab/im-interface:latest  # Use the same image as the main app container
          command:
            - sh
            - -c
            - |
              # Ensure proper ownership of files in /var/www
              chown -R www-data:www-data /var/www
              composer update
              php artisan key:generate --force
              php artisan migrate --force
              php artisan db:seed --force
          env:
            - name: DB_HOST
              value: mysql-db  # Ensure it points to the correct MySQL service
            - name: DB_DATABASE
              value: iim_interface
            - name: DB_USERNAME
              value: user
            - name: DB_PASSWORD
              value: password
          volumeMounts:
            - name: app-data
              mountPath: /var/www  # Ensure it's the right location for your app code
      containers:
        - name: im-interface
          image: harbor.vgregion.se/senslab/im-interface:latest
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql-db  # Ensure it points to the correct MySQL service
            - name: DB_DATABASE
              value: iim_interface
            - name: DB_USERNAME
              value: user
            - name: DB_PASSWORD
              value: password
          volumeMounts:
            - name: app-data
              mountPath: /var/www  # Ensure it's the right location for your app code
        - name: nginx
          image: harbor.vgregion.se/senslab/nginx:latest
          ports:
            - containerPort: 80
      volumes:
        - name: app-data
          emptyDir: {}  # Temporary storage. You can replace this with persistent storage if needed.
