apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-interface
  namespace: im-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: im-interface
  template:
    metadata:
      labels:
        app: im-interface
    spec:
      containers:
        - name: im-interface
          image: harbor.vgregion.se/senslab/im-interface:latest
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql-db
        - name: mysql-db
          image: harbor.vgregion.se/senslab/mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: iim_interface
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
        - name: nginx
          image: harbor.vgregion.se/senslab/nginx:latest
          ports:
            - containerPort: 80
