apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-interface-deployment
  namespace: im-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: im-interface
  template:
    metadata:
      labels:
        app: im-interface
    spec:
      imagePullSecrets:
        - name: harbor
      containers:
        - name: im-interface
          image: harbor.vgregion.se/senslab/im-interface:latest
          command: ["/start.sh"]
          env:
            - name: DB_HOST
              value: mysql-db
            - name: DB_DATABASE
              value: iim_interface
            - name: DB_USERNAME
              value: user
            - name: DB_PASSWORD
              value: password
          ports:
            - containerPort: 9000
            - containerPort: 80
