apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-interface-deployment
  namespace: im-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: im-interface
  template:
    metadata:
      labels:
        app: im-interface
    spec:
      imagePullSecrets:
        - name: harbor
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: im-interface
          image: harbor.vgregion.se/senslab/im-interface:latest
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql-db
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - name: nginx
          image: harbor.vgregion.se/senslab/nginx:latest
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
