apiVersion: v1
kind: Service
metadata:
  name: im-interface-service
  namespace: im-interface
spec:
  selector:
    app: im-interface
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: fpm
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
