apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: im-interface
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        server {
            listen 80;
            server_name senslab-test.k8s.vgregion.se;

            location / {
                root        /var/www/public;
                index       index.html;
                try_files   $uri $uri/ /index.html;
            }

            location /css/ {
                alias /var/www/resources/css/;
                try_files $uri $uri/ =404;
            }

            location /js/ {
                alias /var/www/resources/js/;
                try_files $uri $uri/ =404;
            }

            location /media/ {
                alias /var/www/resources/media/;
                try_files $uri $uri/ =404;
            }

            location ~ \.php$ {
                     fastcgi_split_path_info ^(.+\.php)(/.+)$;
                    fastcgi_pass im-interface-service:9000;
                    fastcgi_index index.php;
                    include fastcgi_params;
                    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                     fastcgi_param PATH_INFO $fastcgi_path_info;
            }
            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }

            client_max_body_size 100M;
        }
    }
